/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddtableRouteImport } from './routes/Addtable'
import { Route as TablesManagmentRouteImport } from './routes/TablesManagment'
import { Route as AccountSuccessRouteImport } from './routes/accountSuccess'
import { Route as AccountVerificationRouteImport } from './routes/accountVerification'
import { Route as ChangePasswordRouteImport } from './routes/changePassword'
import { Route as ChangePasswordErrorRouteImport } from './routes/changePasswordError'
import { Route as ChangePasswordSuccessRouteImport } from './routes/changePasswordSuccess'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditMenuRouteImport } from './routes/editMenu'
import { Route as ForgotPasswordRouteImport } from './routes/forgotPassword'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuManagmentRouteImport } from './routes/menuManagment'
import { Route as PasswordSuccessRouteImport } from './routes/passwordSuccess'
import { Route as ProfileSettingsRouteImport } from './routes/profileSettings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/resetPassword'
import { Route as SimpleDishFormRouteImport } from './routes/simpleDishForm'
import { Route as UnexpectedIssueRouteImport } from './routes/unexpectedIssue'
import { Route as UnexpectedIssueVRouteImport } from './routes/unexpectedIssueV'
import { Route as VerificationCodeRouteImport } from './routes/verificationCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddtableRoute = AddtableRouteImport.update({
  id: '/Addtable',
  path: '/Addtable',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesManagmentRoute = TablesManagmentRouteImport.update({
  id: '/TablesManagment',
  path: '/TablesManagment',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSuccessRoute = AccountSuccessRouteImport.update({
  id: '/accountSuccess',
  path: '/accountSuccess',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerificationRoute = AccountVerificationRouteImport.update({
  id: '/accountVerification',
  path: '/accountVerification',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/changePassword',
  path: '/changePassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordErrorRoute = ChangePasswordErrorRouteImport.update({
  id: '/changePasswordError',
  path: '/changePasswordError',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordSuccessRoute = ChangePasswordSuccessRouteImport.update({
  id: '/changePasswordSuccess',
  path: '/changePasswordSuccess',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditMenuRoute = EditMenuRouteImport.update({
  id: '/editMenu',
  path: '/editMenu',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuManagmentRoute = MenuManagmentRouteImport.update({
  id: '/menuManagment',
  path: '/menuManagment',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordSuccessRoute = PasswordSuccessRouteImport.update({
  id: '/passwordSuccess',
  path: '/passwordSuccess',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profileSettings',
  path: '/profileSettings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleDishFormRoute = SimpleDishFormRouteImport.update({
  id: '/simpleDishForm',
  path: '/simpleDishForm',
  getParentRoute: () => rootRouteImport,
} as any)
const UnexpectedIssueRoute = UnexpectedIssueRouteImport.update({
  id: '/unexpectedIssue',
  path: '/unexpectedIssue',
  getParentRoute: () => rootRouteImport,
} as any)
const UnexpectedIssueVRoute = UnexpectedIssueVRouteImport.update({
  id: '/unexpectedIssueV',
  path: '/unexpectedIssueV',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationCodeRoute = VerificationCodeRouteImport.update({
  id: '/verificationCode',
  path: '/verificationCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Addtable': typeof AddtableRoute
  '/TablesManagment': typeof TablesManagmentRoute
  '/accountSuccess': typeof AccountSuccessRoute
  '/accountVerification': typeof AccountVerificationRoute
  '/changePassword': typeof ChangePasswordRoute
  '/changePasswordError': typeof ChangePasswordErrorRoute
  '/changePasswordSuccess': typeof ChangePasswordSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/editMenu': typeof EditMenuRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menuManagment': typeof MenuManagmentRoute
  '/passwordSuccess': typeof PasswordSuccessRoute
  '/profileSettings': typeof ProfileSettingsRoute
  '/register': typeof RegisterRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/simpleDishForm': typeof SimpleDishFormRoute
  '/unexpectedIssue': typeof UnexpectedIssueRoute
  '/unexpectedIssueV': typeof UnexpectedIssueVRoute
  '/verificationCode': typeof VerificationCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Addtable': typeof AddtableRoute
  '/TablesManagment': typeof TablesManagmentRoute
  '/accountSuccess': typeof AccountSuccessRoute
  '/accountVerification': typeof AccountVerificationRoute
  '/changePassword': typeof ChangePasswordRoute
  '/changePasswordError': typeof ChangePasswordErrorRoute
  '/changePasswordSuccess': typeof ChangePasswordSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/editMenu': typeof EditMenuRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menuManagment': typeof MenuManagmentRoute
  '/passwordSuccess': typeof PasswordSuccessRoute
  '/profileSettings': typeof ProfileSettingsRoute
  '/register': typeof RegisterRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/simpleDishForm': typeof SimpleDishFormRoute
  '/unexpectedIssue': typeof UnexpectedIssueRoute
  '/unexpectedIssueV': typeof UnexpectedIssueVRoute
  '/verificationCode': typeof VerificationCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Addtable': typeof AddtableRoute
  '/TablesManagment': typeof TablesManagmentRoute
  '/accountSuccess': typeof AccountSuccessRoute
  '/accountVerification': typeof AccountVerificationRoute
  '/changePassword': typeof ChangePasswordRoute
  '/changePasswordError': typeof ChangePasswordErrorRoute
  '/changePasswordSuccess': typeof ChangePasswordSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/editMenu': typeof EditMenuRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menuManagment': typeof MenuManagmentRoute
  '/passwordSuccess': typeof PasswordSuccessRoute
  '/profileSettings': typeof ProfileSettingsRoute
  '/register': typeof RegisterRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/simpleDishForm': typeof SimpleDishFormRoute
  '/unexpectedIssue': typeof UnexpectedIssueRoute
  '/unexpectedIssueV': typeof UnexpectedIssueVRoute
  '/verificationCode': typeof VerificationCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Addtable'
    | '/TablesManagment'
    | '/accountSuccess'
    | '/accountVerification'
    | '/changePassword'
    | '/changePasswordError'
    | '/changePasswordSuccess'
    | '/dashboard'
    | '/editMenu'
    | '/forgotPassword'
    | '/login'
    | '/menuManagment'
    | '/passwordSuccess'
    | '/profileSettings'
    | '/register'
    | '/resetPassword'
    | '/simpleDishForm'
    | '/unexpectedIssue'
    | '/unexpectedIssueV'
    | '/verificationCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Addtable'
    | '/TablesManagment'
    | '/accountSuccess'
    | '/accountVerification'
    | '/changePassword'
    | '/changePasswordError'
    | '/changePasswordSuccess'
    | '/dashboard'
    | '/editMenu'
    | '/forgotPassword'
    | '/login'
    | '/menuManagment'
    | '/passwordSuccess'
    | '/profileSettings'
    | '/register'
    | '/resetPassword'
    | '/simpleDishForm'
    | '/unexpectedIssue'
    | '/unexpectedIssueV'
    | '/verificationCode'
  id:
    | '__root__'
    | '/'
    | '/Addtable'
    | '/TablesManagment'
    | '/accountSuccess'
    | '/accountVerification'
    | '/changePassword'
    | '/changePasswordError'
    | '/changePasswordSuccess'
    | '/dashboard'
    | '/editMenu'
    | '/forgotPassword'
    | '/login'
    | '/menuManagment'
    | '/passwordSuccess'
    | '/profileSettings'
    | '/register'
    | '/resetPassword'
    | '/simpleDishForm'
    | '/unexpectedIssue'
    | '/unexpectedIssueV'
    | '/verificationCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddtableRoute: typeof AddtableRoute
  TablesManagmentRoute: typeof TablesManagmentRoute
  AccountSuccessRoute: typeof AccountSuccessRoute
  AccountVerificationRoute: typeof AccountVerificationRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ChangePasswordErrorRoute: typeof ChangePasswordErrorRoute
  ChangePasswordSuccessRoute: typeof ChangePasswordSuccessRoute
  DashboardRoute: typeof DashboardRoute
  EditMenuRoute: typeof EditMenuRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MenuManagmentRoute: typeof MenuManagmentRoute
  PasswordSuccessRoute: typeof PasswordSuccessRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimpleDishFormRoute: typeof SimpleDishFormRoute
  UnexpectedIssueRoute: typeof UnexpectedIssueRoute
  UnexpectedIssueVRoute: typeof UnexpectedIssueVRoute
  VerificationCodeRoute: typeof VerificationCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Addtable': {
      id: '/Addtable'
      path: '/Addtable'
      fullPath: '/Addtable'
      preLoaderRoute: typeof AddtableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TablesManagment': {
      id: '/TablesManagment'
      path: '/TablesManagment'
      fullPath: '/TablesManagment'
      preLoaderRoute: typeof TablesManagmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountSuccess': {
      id: '/accountSuccess'
      path: '/accountSuccess'
      fullPath: '/accountSuccess'
      preLoaderRoute: typeof AccountSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountVerification': {
      id: '/accountVerification'
      path: '/accountVerification'
      fullPath: '/accountVerification'
      preLoaderRoute: typeof AccountVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changePassword': {
      id: '/changePassword'
      path: '/changePassword'
      fullPath: '/changePassword'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changePasswordError': {
      id: '/changePasswordError'
      path: '/changePasswordError'
      fullPath: '/changePasswordError'
      preLoaderRoute: typeof ChangePasswordErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changePasswordSuccess': {
      id: '/changePasswordSuccess'
      path: '/changePasswordSuccess'
      fullPath: '/changePasswordSuccess'
      preLoaderRoute: typeof ChangePasswordSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editMenu': {
      id: '/editMenu'
      path: '/editMenu'
      fullPath: '/editMenu'
      preLoaderRoute: typeof EditMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menuManagment': {
      id: '/menuManagment'
      path: '/menuManagment'
      fullPath: '/menuManagment'
      preLoaderRoute: typeof MenuManagmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwordSuccess': {
      id: '/passwordSuccess'
      path: '/passwordSuccess'
      fullPath: '/passwordSuccess'
      preLoaderRoute: typeof PasswordSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profileSettings': {
      id: '/profileSettings'
      path: '/profileSettings'
      fullPath: '/profileSettings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simpleDishForm': {
      id: '/simpleDishForm'
      path: '/simpleDishForm'
      fullPath: '/simpleDishForm'
      preLoaderRoute: typeof SimpleDishFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unexpectedIssue': {
      id: '/unexpectedIssue'
      path: '/unexpectedIssue'
      fullPath: '/unexpectedIssue'
      preLoaderRoute: typeof UnexpectedIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unexpectedIssueV': {
      id: '/unexpectedIssueV'
      path: '/unexpectedIssueV'
      fullPath: '/unexpectedIssueV'
      preLoaderRoute: typeof UnexpectedIssueVRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificationCode': {
      id: '/verificationCode'
      path: '/verificationCode'
      fullPath: '/verificationCode'
      preLoaderRoute: typeof VerificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddtableRoute: AddtableRoute,
  TablesManagmentRoute: TablesManagmentRoute,
  AccountSuccessRoute: AccountSuccessRoute,
  AccountVerificationRoute: AccountVerificationRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ChangePasswordErrorRoute: ChangePasswordErrorRoute,
  ChangePasswordSuccessRoute: ChangePasswordSuccessRoute,
  DashboardRoute: DashboardRoute,
  EditMenuRoute: EditMenuRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MenuManagmentRoute: MenuManagmentRoute,
  PasswordSuccessRoute: PasswordSuccessRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimpleDishFormRoute: SimpleDishFormRoute,
  UnexpectedIssueRoute: UnexpectedIssueRoute,
  UnexpectedIssueVRoute: UnexpectedIssueVRoute,
  VerificationCodeRoute: VerificationCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
